### ISSUE TITLE
Problem with Fusion Annotation

### ISSUE THREAD

**Issue by MesudeBicak** [TRON-Bioinformatics/EasyFuse#55]
Hi EasyFuse Team,

I am excited to try out your tool and successfully made it till FUSION_ANNOTATION step (see below), but struggling to move past the current error I am getting - please see below:

[bicakm01@lh06c11 EasyFuse]$ nextflow main.nf -profile conda --reference test/easyfuse_ref --input_files ../easyfuse-input-file --output ../easyFuseOutputs/ -resume
N E X T F L O W  ~  version 21.10.0
Launching `main.nf` [magical_hugle] - revision: 3d2972589c
executor >  local (1)
[c8/c11c69] process > QC:FASTQC (sample_01)                    [100%] 1 of 1, cached: 1 ✔
[85/1e4789] process > QC:FASTQC_PARSER (sample_01)             [100%] 1 of 1, cached: 1 ✔
[f0/b8f122] process > QC:SKEWER (sample_01)                    [100%] 1 of 1, cached: 1 ✔
[ec/2aeca7] process > ALIGNMENT:STAR (sample_01)               [100%] 1 of 1, cached: 1 ✔
[86/4aa8c2] process > ALIGNMENT:READ_FILTER (sample_01)        [100%] 1 of 1, cached: 1 ✔
[6c/b658ad] process > ALIGNMENT:BAM2FASTQ (sample_01)          [100%] 1 of 1, cached: 1 ✔
[c9/2f22b2] process > TOOLS:FUSION_CATCHER (sample_01)         [100%] 1 of 1, cached: 1 ✔
[20/4efcc2] process > TOOLS:STAR_FUSION (sample_01)            [100%] 1 of 1, cached: 1 ✔
[40/688a67] process > ANNOTATION:FUSION_PARSER (sample_01)     [100%] 1 of 1, cached: 1 ✔
[f3/03b307] process > ANNOTATION:FUSION_ANNOTATION (sample_01) [  0%] 0 of 1
[-        ] process > REQUANTIFICATION:FUSION_FILTER           -
[-        ] process > REQUANTIFICATION:BAM2FASTQ               -
[-        ] process > REQUANTIFICATION:STAR_INDEX              -
[-        ] process > REQUANTIFICATION:STAR_CUSTOM             -
[-        ] process > REQUANTIFICATION:READ_COUNT              -
[-        ] process > SUMMARIZE_DATA                           -

Command executed:

  easy-fuse annotation         --detected_fusions Detected_Fusions.csv         --annotation_db /sc/arion/projects/bhardwajLab/MesudeBicak/EasyFuse/test/easyfuse_ref/Homo_sapiens.GRCh38.110.gff3.db         --out_csv annotated_fusions.csv         --genome_fasta /sc/arion/projects/bhardwajLab/MesudeBicak/EasyFuse/test/easyfuse_ref/Homo_sapiens.GRCh38.dna.primary_assembly.fa         --tsl_info /sc/arion/projects/bhardwajLab/MesudeBicak/EasyFuse/test/easyfuse_ref/Homo_sapiens.GRCh38.110.gtf.tsl         --cis_near_dist 1000000         --context_seq_len 400         --tsl_filter_level 4,5,NA

Command exit status:
  1

Command output:
  (empty)

Command error:
  [D 240214 13:12:04 fusionannotation:517] Annotating "10:100354618:+_14:49862689:-"...
  Traceback (most recent call last):
    File "/sc/arion/projects/bhardwajLab/MesudeBicak/EasyFuse/work/conda/easyfuse_src-c203347e504f3b4d10ed96fdd01318ce/bin/easy-fuse", line 11, in <module>
      sys.exit(easy_fuse_cli())
    File "/sc/arion/projects/bhardwajLab/MesudeBicak/EasyFuse/work/conda/easyfuse_src-c203347e504f3b4d10ed96fdd01318ce/lib/python3.7/site-packages/pyeasyfuse/command_line.py", line 127, in easy_fuse_cli
      args.func(args)
    File "/sc/arion/projects/bhardwajLab/MesudeBicak/EasyFuse/work/conda/easyfuse_src-c203347e504f3b4d10ed96fdd01318ce/lib/python3.7/site-packages/pyeasyfuse/fusionannotation.py", line 1275, in annotation_command
      args.tsl_filter_level,
    File "/sc/arion/projects/bhardwajLab/MesudeBicak/EasyFuse/work/conda/easyfuse_src-c203347e504f3b4d10ed96fdd01318ce/lib/python3.7/site-packages/pyeasyfuse/fusionannotation.py", line 591, in run
      ) = self.get_parents(bp2_efeature)
    File "/sc/arion/projects/bhardwajLab/MesudeBicak/EasyFuse/work/conda/easyfuse_src-c203347e504f3b4d10ed96fdd01318ce/lib/python3.7/site-packages/pyeasyfuse/fusionannotation.py", line 205, in get_parents
      gene_name = parent.attributes["Name"][0]
    File "/sc/arion/projects/bhardwajLab/MesudeBicak/EasyFuse/work/conda/easyfuse_src-c203347e504f3b4d10ed96fdd01318ce/lib/python3.7/site-packages/gffutils/attributes.py", line 63, in __getitem__
      v = self._d[k]
  KeyError: 'Name'

Work dir:
  /sc/arion/projects/bhardwajLab/MesudeBicak/EasyFuse/work/f3/03b307b3d1c38ce0ae3552d570885d

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

I checked the annotation_db /sc/arion/projects/bhardwajLab/MesudeBicak/EasyFuse/test/easyfuse_ref/Homo_sapiens.GRCh38.110.gff3.db and "Name" is indeed there.

I would greatly appreciate any pointers.

Best wishes,
Mesude

**Comment by ibn-salem** [comment]
This seems to be an outdated version of EasyFuse. Please use the latest version and try again.
