### ISSUE TITLE
Fetchdata error

### ISSUE THREAD

**Issue by Xiaoguang-Shi** [TRON-Bioinformatics/EasyFuse#8]
Hello  @ibn-salem @priesgo @ozlemmuslu @martinloewer @mostafiz2010 
I'm having some problems with Easyfuse. At first, the test data is ok, and  get  results. But there is a problem in the Step Fetchdata , when I use my own data. And the previous steps all seem to work fine.
```
...
Running 
CMD: ['/public/home/miniconda3/envs/easyfuse/bin/samtools', 'index', '/public/home/data/neoantigen/RNA/fusion_easyfuse/sample1/Sample_sample1/fetchdata/fd_1_tool/fetched_contextseqs/STAR_align/sample1_best_Aligned.sortedByCoord.out.bam']

Running 
CMD: ['/public/home/rp1001wsy/xiaoguang/biosoft/EasyFuse-1.3.4/requantify.py', '-i', '/public/home/data/neoantigen/RNA/fusion_easyfuse/sample1/Sample_sample1/fetchdata/fd_1_tool/fetched_contextseqs/STAR_align/sample1_best_Aligned.sortedByCoord.out.bam', '-o', '/public/home/data/neoantigen/RNA/fusion_easyfuse/sample1/Sample_sample1/fetchdata/fd_1_tool/classification/classification_best.tdt', '-d', '10']
Found 105641 potential fusion sequences
Error: Command "['/public/home/biosoft/EasyFuse-1.3.4/requantify.py', '-i', '/public/home/RNA/fusion_easyfuse/sample1/Sample_sample1/fetchdata/fd_1_tool/fetched_contextseqs/STAR_align/sample1_best_Aligned.sortedByCoord.out.bam', '-o', '/public/home/RNA/fusion_easyfuse/sample1/Sample_sample1/fetchdata/fd_1_tool/classification/classification_best.tdt', '-d', '10']" returned non-zero exit status
Traceback (most recent call last):
  File "/public/home/biosoft/EasyFuse-1.3.4/requantify.py", line 236, in <module>
    main()
  File "/public/home/biosoft/EasyFuse-1.3.4/requantify.py", line 233, in main
    requant.run()
  File "/public/home/biosoft/EasyFuse-1.3.4/requantify.py", line 169, in run
    self.quantify_read_groups(read_buffer, last_reference)
  File "/public/home/biosoft/EasyFuse-1.3.4/requantify.py", line 62, in quantify_read_groups
    self.fusion_seq_dict[reference_base][5] = anchor_ft
KeyError: ''
```

**Comment by priesgo** [comment]
@sorn ping

**Comment by Xiaoguang-Shi** [comment]
This is the log file I get from running Fetchdata, where error.log is empty.
[fetchdata.log](https://github.com/TRON-Bioinformatics/EasyFuse/files/8896562/fetchdata.log)
[output.log](https://github.com/TRON-Bioinformatics/EasyFuse/files/8896630/output.log)
[Log.out.zip](https://github.com/TRON-Bioinformatics/EasyFuse/files/8896697/Log.out.zip)

**Comment by ibn-salem** [comment]
Dear @Xiaoguang-Shi, 
thank you for reporting this issue. Can you please try to repeat the run with the latest version of EasyFuse?
Thank you.

**Comment by BGI2016** [comment]
> Dear @Xiaoguang-Shi, thank you for reporting this issue. Can you please try to repeat the run with the latest version of EasyFuse? Thank you.

Dear @ibn-salem , I used the latest version of the EasyFuse to analyze my own data, and I encountered the same problem.

**Comment by ibn-salem** [comment]
Hi, it seems to be a specific issue with the context sequences (fusion candidates) of your sample. 
Can you send us this file:
`/public/home/data/neoantigen/RNA/fusion_easyfuse/sample1/Sample_sample1/fetchdata/fd_1_tool/fetched_contextseqs/Context_Seqs.csv`
Thanks

**Comment by xiaoguang-sjtu** [comment]
Hi, Thank you for your reply. This problem seems to have disappeared when I used the latest version of  EasyFuse. Since our HPC does not support Docker, I converted it with singularity. The whole process was not very smooth, there was a little problem with the FusionSummary step. And it took more than one day for each sample with 40 CPUs.The output results were puzzling. Over 1000 fusion genes were obtained from each sample, but could not be verified by single molecule sequencing (ONT), which I think may be due to the defect of NGS.

Translated with www.DeepL.com/Translator (free version)

**Comment by XM-UChicago** [comment]
Hi @ibn-salem , I have the same issue with the latest version (1.3.6). I felt the problem is related to fetchdata.py. I found the command "samtools fastq -0 sample_1.fq.gz -1 sample_1.fq.gz -2 sample_2.fq.gz --threads 3 sample_Aligned.out.filtered2.bam" in log. First, "sample_1.fq.gz" was used for both -0 and -1. I don't know whether you need read in -0. I felt it better to change it to a different file (e.g. sample_0.fq.gz). Second, the context of sample_1.fq.gz would be "gzip: sample_1.fq.gz: decompression OK, trailing garbage ignored". I guess this lead to the issue. since the bam, which base on these two fq files would be empty. It is weired that the sample_1.fq is correct with your test data.

**Comment by ibn-salem** [comment]
Hi, we assume that you could fix this by renaming the fastq files. Feel free to re-open if needed.
